# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Fact.create(fact:"He gave his father 'the talk'.")
Fact.create(fact:"His passport requires no photograph.")
Fact.create(fact:"He never says something tastes like chicken.. not even chicken.")
Fact.create(fact:"Superman has pijamas with his logo.")
Fact.create(fact:"His tears can cure cancer, too bad he never cries.")
Fact.create(fact:" He can speak Russian… in French.")
Fact.create(fact:"Whatever side of the tracks he’s currently on is the right side, even if he crosses the tracks he’ll still be on the right side.")
Fact.create(fact:"If he were to punch you in the face you would have to fight off a strong urge to thank him.")
Fact.create(fact:" He once went to the psychic, to warn her.")
Fact.create(fact:"His feet don’t get blisters, but his shoes do.")
Fact.create(fact:" His 5 de Mayo party starts on the 8th of March.")
Fact.create(fact:"Once a rattlesnake bit him, after 5 days of excruciating pain, the snake finally died.")
Fact.create(fact:" When he drives a car off the lot, its price increases in value.")
Fact.create(fact:"He once brought a knife to a gunfight… just to even the odds.")
Fact.create(fact:"When he meets the Pope, the Pope kisses his ring.")
Fact.create(fact:"Bear hugs are what he gives bears.")
Fact.create(fact:"The circus ran away to join him.")
Fact.create(fact:"His friends call him by his name, his enemies don’t call him anything because they are all dead.")
Fact.create(fact:"He has never waited 15 minutes after finishing a meal before returning to the pool.")
Fact.create(fact:"If he were to visit the dark side of the moon, it wouldn’t be dark.")
Fact.create(fact:"He once won a staring contest with his own reflection.")
Fact.create(fact:"He can kill two stones with one bird.")
Fact.create(fact:"His signature won a Pulitzer.")
Fact.create(fact:"When a tree falls in a forest and no one is there, he hears it
He once got pulled over for speeding, and the cop got the ticket.")

Fact.create(fact:"The dark is afraid of him.")
Fact.create(fact:"Sharks have a week dedicated to him.")
Fact.create(fact:"His ten gallon hat holds twenty gallons.")
Fact.create(fact:"No less than 25 Mexican folk songs have been written about his beard.")
Fact.create(fact:"He once made a weeping willow laugh.")
Fact.create(fact:"He lives vicariously through himself.")
Fact.create(fact:"His business card simply says ‘I’ll Call You.'")
Fact.create(fact:"He once taught a German shepherd how to bark in Spanish")
Fact.create(fact:"He bowls overhand.")
Fact.create(fact:"In museums, he is allowed to touch the art")
Fact.create(fact:"He is allowed to talk about fight club..")
Fact.create(fact:"He once won a fist fight, only using his beard.")
Fact.create(fact:"He once won the Tour-de-France, but was disqualified for riding a unicycle.")
Fact.create(fact:"A bird in his hand is worth three in the bush.")
Fact.create(fact:"His lovemaking has been detected by a seismograph.")
Fact.create(fact:"The Holy Grail is looking for him.")
Fact.create(fact:"Roses stop to smell him.")
Fact.create(fact:"He once started a fire using only dental floss and water.")
Fact.create(fact:"His sweat is the cure for the common cold.")
Fact.create(fact:"Bigfoot tries to get pictures of him.")
Fact.create(fact:"Werewolves are jealous of his beard.")
Fact.create(fact:"He once turned a vampire into a vegetaria.n")
Fact.create(fact:"He once won the world series of poker using UNO cards.")
Fact.create(fact:"He never wears a watch because time is always on his side.")
Fact.create(fact:"He has taught old dogs a variety of new tricks.")
Fact.create(fact:"He has won the lifetime achievement award… twice.")
Fact.create(fact:"If opportunity knocks, and he’s not at home, opportunity waits.")
Fact.create(fact:"Batman watches Saturday morning cartoons about him.")
Fact.create(fact:"When he was young he once sent his parents to his room.")
Fact.create(fact:"He once had an awkward moment, just to see how it feels.")
Fact.create(fact:"His beard alone has experienced more than a lesser man’s entire body.")
Fact.create(fact:"His blood smells like cologne.")
Fact.create(fact:"On every continent in the world, there is a sandwich named after him.")
Fact.create(fact:"Mosquitoes refuse to bite him purely out of respect.")
Fact.create(fact:"He is fluent in all languages, including three that he only speaks.")
Fact.create(fact:"Once while sailing around the world, he discovered a short cut.")
Fact.create(fact:"Panhandlers give him money.")
Fact.create(fact:"When he goes to Spain, he chases the bulls.")
Fact.create(fact:"His shadow has been on the ‘best dressed’ list twice.")
Fact.create(fact:"When he holds a lady’s purse, he looks manly.")
Fact.create(fact:"Two countries went to war to dispute HIS nationality.")
Fact.create(fact:"When in Rome, they do as HE does.")
Fact.create(fact:"His pillow is cool on BOTH sides.")
Fact.create(fact:"The Nobel Academy was awarded a prize from HIM.")

Fact.create(fact:"He taught Chuck Norris martial arts.")
Fact.create(fact:"Time waits on no one, but him.")
Fact.create(fact:"Once he ran a marathon because it was “on the way”.")
Fact.create(fact:"His mother has a tattoo that says “Son”.")
Fact.create(fact:"The star on his Christmas tree is tracked by NASA.")
Fact.create(fact:"Presidents take his birthday off.")
Fact.create(fact:"His shirts never wrinkle.")
Fact.create(fact:"He has never walked into a spider web.")
Fact.create(fact:"He is left-handed. And right-handed.")
Fact.create(fact:"His shirts never wrinkle.")
Fact.create(fact:"The police often question him, just because they find him interesting.")
Fact.create(fact:"His organ donation card also lists his beard")
Fact.create(fact:"He doesn’t believe in using oven mitts, nor potholders")
Fact.create(fact:"His cereal never gets soggy. It sits there, staying crispy, just for him")
Fact.create(fact:"Respected archaeologists fight over his discarded apple cores")
Fact.create(fact:"Even his tree houses have fully finished basements")
Fact.create(fact:"His garden maze is responsible for more missing persons than the bermuda triangle")
Fact.create(fact:"If he were to say something costs an arm and a leg, it would")
Fact.create(fact:"He’s never lost a game of chance.")
Fact.create(fact:"He is the life of parties that he has never attended.")

Fact.create(fact:"He once caught the Loch Ness Monster….with a cane pole, but threw it back.")
Fact.create(fact:"His wallet is woven out of chupacabra leather")
Fact.create(fact:"He played a game of Russian Roulette with a fully loaded magnum, and won.")
Fact.create(fact:"Freemasons strive to learn HIS secret handshake.")
Fact.create(fact:"If he was to pat you on the back, you would list it on your resume.")
Fact.create(fact:"He is considered a national treasure in countries he’s never visited.")
Fact.create(fact:"Cars look both ways for him, before driving down a street.")
Fact.create(fact:"He once tried to acquire a cold just to see what it felt like, but it didn’t take.")
Fact.create(fact:"He has inside jokes with people he’s never met.")
Fact.create(fact:"He has never filled up on chips.")
Fact.create(fact:"Bikers walk their motorcycles past his home.")
Fact.create(fact:"He has inside jokes with complete strangers.")
